KAFKA_BOOTSTRAP_SERVERS=localhost:19092,localhost:29092
KAFKA_SCHEMA_REGISTRY=http://localhost:8081
KAFKA_SCHEMA_AUTO_REGISTER=true
KAFKA_PRODUCER_CLIENT_ID=github-accounts-publisher
KAFKA_ENABLE_IDEMPOTENCE=true
KAFKA_PRODUCER_ACKS=all
KAFKA_GITHUB_ACCOUNTS_TOPIC=github-accounts
GITHUB_ACCOUNTS_LIST_FILENAME=/tmp/github-accounts.txt
