services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:${CONF_VER}"
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - 2181:2181
    volumes:
      - zookeeper:/var/lib/zookeeper/data
    environment:
      TZ: ${TIMEZONE}
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: "confluentinc/cp-kafka:${CONF_VER}"
    restart: unless-stopped
    depends_on:
      - zookeeper
    container_name: kafka1
    ports:
      - 19092:9092
    volumes:
      - kafka1:/var/lib/kafka/data
    environment:
      TZ: ${TIMEZONE}
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      CONFLUENT_METRICS_ENABLE: 'false'

  kafka2:
    image: "confluentinc/cp-kafka:${CONF_VER}"
    restart: unless-stopped
    depends_on:
      - zookeeper
    container_name: kafka2
    ports:
      - 29092:9092
    volumes:
      - kafka2:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      TZ: ${TIMEZONE}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      CONFLUENT_METRICS_ENABLE: 'false'

  schema-registry:
    image: "confluentinc/cp-schema-registry:${CONF_VER}"
    container_name: schema-registry
    ports:
      - 8081:8081
    depends_on:
      - kafka1
      - kafka2
    environment:
      TZ: ${TIMEZONE}
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 2
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: "none"
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: "WARN"

  kafka-ui:
    container_name: kafka-ui
    image: ghcr.io/kafbat/kafka-ui:v1.4.2
    depends_on:
      - kafka1
      - kafka2
    ports:
      - 8082:8082
    environment:
      SERVER_PORT: 8082
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: 'gridu-kafka-local-cluster'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka1:9092,kafka2:9092'
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: 'http://schema-registry:8081'

  github-accounts-publisher:
    container_name: github-accounts-publisher
    image: github-accounts-publisher:latest
    restart: no
    depends_on:
      - kafka1
      - kafka2
    volumes:
      - ./github-accounts.txt:/tmp/github-accounts.txt
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092
      KAFKA_SCHEMA_REGISTRY: http://schema-registry:8081
      KAFKA_SCHEMA_AUTO_REGISTER: true
      KAFKA_PRODUCER_CLIENT_ID: github-accounts-publisher
      KAFKA_ENABLE_IDEMPOTENCE: true
      KAFKA_GITHUB_ACCOUNTS_TOPIC: github-accounts
      GITHUB_ACCOUNTS_LIST_FILENAME: /tmp/github-accounts.txt

#  ksqldb-server:
#    image: confluentinc/cp-ksqldb-server:${KSQLDB_VER}
#    hostname: ksqldb-server
#    container_name: ksqldb-server
#    depends_on:
#      - kafka
#      - kafka-connect
#      - schema-registry
#    ports:
#      - "8088:8088"
#    environment:
#      KSQL_LISTENERS: http://0.0.0.0:8088
#      KSQL_BOOTSTRAP_SERVERS: kafka:29092
#      KSQL_KSQL_CONNECT_URL: http://kafka-connect:8083
#      KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:8081
#      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
#      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
#      KSQL_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
#      KSQL_KSQL_EXTENSION_DIR: "/etc/ksql/ext"
#    volumes:
#      - ./scripts:/scripts
#      - ./ext:/etc/ksql/ext
#
#  ksqldb-cli:
#    image: confluentinc/cp-ksqldb-cli:${KSQLDB_VER}
#    container_name: ksqldb-cli
#    depends_on:
#      - kafka
#      - ksqldb-server
#    volumes:
#      - ./user_profile_pretty.ksql:/user_profile_pretty.ksql
#    entrypoint: /bin/sh
#    tty: true

#  kafka-connect:
#    container_name: kafka-connect
#    image: confluentinc/cp-kafka-connect:${CONNECT_VER}
#    depends_on:
#      - zookeeper
#      - kafka
#      - schema-registry
#    ports:
#      - '8083:8083'
#    environment:
#      TZ: ${TIMEZONE}
#      CONNECT_BOOTSTRAP_SERVERS: "kafka:29092"
#      CONNECT_REST_PORT: 8083
#      CONNECT_GROUP_ID: compose-connect-group
#      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
#      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
#      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
#      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
#      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
#      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
#      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
#      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
#      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
#      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
#      CONNECT_PLUGIN_PATH: /usr/share/java
#      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
#      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
#      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
#      CONNECT_CONFLUENT_TOPIC_REPLICATION_FACTOR: 1
#    volumes:
#      - ./container-data/kafka-connect/kafka-connect-rest:/usr/share/java/kafka-connect-rest
#      #   - ./confluentinc-kafka-connect-mqtt:/usr/share/java/confluentinc-kafka-connect-mqtt
#
#  postgres:
#    container_name: postgres
#    image: 'postgres:${PG_VER}'
#    hostname: postgres
#    ports:
#      - "5432:5432"
#    environment:
#      TZ: ${TIMEZONE}
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: ${POSTGRES_SRC_PASSWORD}
#      POSTGRES_DB: postgres
#    #    PGDATA: /var/lib/postgresql/data/pgdata
#    volumes:
#      - ./postgres-setup.sql:/postgres-setup.sql
#
#  spring-boot:
#    image: openjdk:alpine
#    hostname: spring-boot
#    networks:
#      - default
#    ports:
#      - "8080:28080"
#    volumes:
#      - ${PWD}/build/libs:/tmp
#    command: ["java", "-jar", "/tmp/*.jar"]
volumes:
  kafka1:
    driver: local
  kafka2:
    driver: local
  zookeeper:
    driver: local
