KAFKA_BOOTSTRAP_SERVERS=localhost:19092,localhost:29092
KAFKA_STREAMS_APPLICATION_ID=github-commits-metrics-stream
KAFKA_SCHEMA_REGISTRY=http://localhost:8081
KAFKA_SCHEMA_AUTO_REGISTER=false

KAFKA_GITHUB_COMMITS_TOPIC=github-commits
KAFKA_GITHUB_METRICS_TOPIC=github-metrics
