KAFKA_BOOTSTRAP_SERVERS=localhost:19092,localhost:29092

KAFKA_SCHEMA_REGISTRY=http://localhost:8081
KAFKA_SCHEMA_AUTO_REGISTER=false

KAFKA_GITHUB_COMMITS_TOPIC=github-commits

UNIQUE_SHA_STATE_STORE=github-commits-sha-state-store

TOP_COMMITTERS_GROUP_SIZE=5
TOP_COMMITTERS_STREAMS_APPLICATION_ID=top-committers-streams-app
TOP_COMMITTERS_CURRENT_TOP_STATE_STORE=top-committers-current-top-state-store
TOP_COMMITTERS_COMMITS_PER_USER_STATE_STORE=top-committers-commits-per-user-state-store
TOP_COMMITTERS_TOPIC=top-committers
TOP_COMMITTERS_KEY=top-committers

TOP_LANGUAGES_GROUP_SIZE=5
TOP_LANGUAGES_STREAMS_APPLICATION_ID=top-languages-streams-app
TOP_LANGUAGES_CURRENT_TOP_STATE_STORE=top-languages-current-top-state-store
TOP_LANGUAGES_COMMITS_PER_LANGUAGE_STATE_STORE=top-languages-commits-per-language-state-store
TOP_LANGUAGES_TOPIC=top-languages
TOP_LANGUAGES_KEY=top-languages

TOTAL_COMMITS_COUNT_STREAMS_APPLICATION_ID=github-commits-total-count-streams-app
TOTAL_COMMITS_COUNT_STATE_STORE=github-commits-total-count-state-store
TOTAL_COMMITS_COUNT_TOPIC=github-commits-total-count
TOTAL_COMMITS_COUNT_KEY=total

TOTAL_COMMITTERS_COUNT_STREAMS_APPLICATION_ID=github-committers-total-count-streams-app
TOTAL_COMMITTERS_COUNT_STATE_STORE=github-committers-total-count-state-store
TOTAL_COMMITTERS_COUNT_TOPIC=github-committers-total-count
TOTAL_COMMITTERS_COUNT_KEY=total
