KAFKA_BOOTSTRAP_SERVERS=localhost:19092,localhost:29092
KAFKA_SCHEMA_REGISTRY=http://localhost:8081

KAFKA_PRODUCER_CLIENT_ID=github-commits-publisher
KAFKA_ENABLE_IDEMPOTENCE=true
KAFKA_SCHEMA_AUTO_REGISTER=true

KAFKA_CONSUMER_GROUP_ID=github-commits-publisher
KAFKA_CONSUMER_AUTO_OFFSET_RESET_CONFIG=earliest
KAFKA_CONSUMER_ENABLE_AUTOCOMMIT=false

KAFKA_GITHUB_ACCOUNTS_TOPIC=github-accounts
KAFKA_GITHUB_COMMITS_TOPIC=github-commits
