KAFKA_BOOTSTRAP_SERVERS=localhost:19092,localhost:29092
KAFKA_SCHEMA_REGISTRY=http://localhost:8081

KAFKA_PRODUCER_CLIENT_ID=github-commits-publisher
KAFKA_PRODUCER_ACKS=all
KAFKA_ENABLE_IDEMPOTENCE=true
KAFKA_SCHEMA_AUTO_REGISTER=false

KAFKA_CONSUMER_GROUP_ID=github-commits-publisher
KAFKA_CONSUMER_AUTO_OFFSET_RESET_CONFIG=earliest
KAFKA_CONSUMER_ENABLE_AUTOCOMMIT=false
KAFKA_CONSUMER_HEARTBEAT_INTERVAL_MS=1000
KAFKA_CONSUMER_SESSION_TIMEOUT_MS=10000

KAFKA_GITHUB_ACCOUNTS_TOPIC=github-accounts
KAFKA_GITHUB_COMMITS_TOPIC=github-commits

GITHUB_API_BASE_URL=https://api.github.com/search/commits

REDIS_HOST=localhost
REDIS_PORT=6379
LANGUAGES_CACHE_ENABLED=true
