KAFKA_BOOTSTRAP_SERVERS=localhost:19092,localhost:29092
KAFKA_SCHEMA_REGISTRY=http://localhost:8081

KAFKA_GITHUB_COMMITS_TOPIC=github-commits

UNIQUE_SHA_STATE_STORE=github-commits-sha-state-store

COMMITS_COUNT_PER_AUTHOR_STREAMS_APPLICATION_ID=github-commits-per-author-streams-app
COMMITS_COUNT_PER_AUTHOR_STATE_STORE=github-commits-per-author-state-store
COMMITS_COUNT_PER_AUTHOR_TOPIC=github-commits-per-author
COMMITS_COUNT_PER_AUTHOR_KEY=github-commits-per-author

TOP_COMMITTERS_GROUP_SIZE=5
TOP_COMMITTERS_CURRENT_TOP_STATE_STORE=top-committers-current-top-state-store
TOP_COMMITTERS_TOPIC=top-committers
TOP_COMMITTERS_KEY=top-committers

COMMITS_COUNT_PER_LANGUAGE_STREAMS_APPLICATION_ID=github-commits-per-language-streams-app
COMMITS_COUNT_PER_LANGUAGE_STATE_STORE=github-commits-per-language-state-store
COMMITS_COUNT_PER_LANGUAGE_TOPIC=github-commits-per-language
COMMITS_COUNT_PER_LANGUAGE_KEY=github-commits-per-language

TOP_LANGUAGES_GROUP_SIZE=5
TOP_LANGUAGES_CURRENT_TOP_STATE_STORE=top-languages-current-top-state-store
TOP_LANGUAGES_TOPIC=top-languages
TOP_LANGUAGES_KEY=top-languages

TOTAL_COMMITS_COUNT_STREAMS_APPLICATION_ID=github-commits-total-count-streams-app
TOTAL_COMMITS_COUNT_STATE_STORE=github-commits-total-count-state-store
TOTAL_COMMITS_COUNT_TOPIC=github-commits-total-count
TOTAL_COMMITS_COUNT_KEY=total

TOTAL_COMMITTERS_COUNT_STREAMS_APPLICATION_ID=github-committers-total-count-streams-app
TOTAL_COMMITTERS_COUNT_STATE_STORE=github-committers-total-count-state-store
TOTAL_COMMITTERS_COUNT_TOPIC=github-committers-total-count
TOTAL_COMMITTERS_COUNT_KEY=total
